var globalData = {};

globalData.matches = [
    {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "RUS",
        team2: "SAU",
        group: "a",
        team1_win: 1.00000000,
        team2_win: 0.00000000,
        tie_prob: 0.00000000,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "EGI",
        team2: "URU",
        group: "a",
        team1_win: 0.00000000,
        team2_win: 1.00000000,
        tie_prob: 0.00000000,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "14:00",
        team1: "POR",
        team2: "ESP",
        group: "b",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "MAR",
        team2: "IRN",
        group: "b",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#fcc41a",
        team1_away_color: "#002B7F",
        team2_home_color: "#ffffff",
        team2_away_color: "#be0000",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "RUS",
        team2: "EGI",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "URU",
        team2: "SAU",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:    0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "11:00",
        team1: "POR",
        team2: "MAR",
        group: "b",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "IRN",
        team2: "ESP",
        group: "b",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "URU",
        team2: "RUS",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "SAU",
        team2: "EGI",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "IRN",
        team2: "POR",
        group: "b",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#00B140",
        team2_away_color: "#FDDA24",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "ESP",
        team2: "MAR",
        group: "b",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#D52B1E",
        team1_away_color: "#ffffff",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "FRA",
        team2: "AUS",
        group: "C",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "PER",
        team2: "DIN",
        group: "c",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "14:00",
        team1: "ARG",
        team2: "ISL",
        group: "d",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "CRO",
        team2: "NGA",
        group: "d",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#fcc41a",
        team1_away_color: "#002B7F",
        team2_home_color: "#ffffff",
        team2_away_color: "#be0000",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "FRA",
        team2: "PER",
        group: "c",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "DIN",
        team2: "AUS",
        group: "c",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "11:00",
        team1: "ARG",
        team2: "CRO",
        group: "d",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "NGA",
        team2: "ISL",
        group: "d",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "DIN",
        team2: "FRA",
        group: "c",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "AUS",
        team2: "PER",
        group: "c",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "NGA",
        team2: "ARG",
        group: "d",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#00B140",
        team2_away_color: "#FDDA24",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "ISL",
        team2: "CRO",
        group: "d",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#D52B1E",
        team1_away_color: "#ffffff",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "BRA",
        team2: "SUI",
        group: "e",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "CRC",
        team2: "SRB",
        group: "e",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "14:00",
        team1: "GER",
        team2: "MEX",
        group: "f",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "SUE",
        team2: "COR",
        group: "f",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#fcc41a",
        team1_away_color: "#002B7F",
        team2_home_color: "#ffffff",
        team2_away_color: "#be0000",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "BRA",
        team2: "CRC",
        group: "e",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "SRB",
        team2: "SUI",
        group: "e",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "11:00",
        team1: "GER",
        team2: "SUE",
        group: "f",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "COR",
        team2: "MEX",
        group: "f",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "SRB",
        team2: "BRA",
        group: "e",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "SUI",
        team2: "CRC",
        group: "e",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "COR",
        team2: "GER",
        group: "f",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#00B140",
        team2_away_color: "#FDDA24",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "MEX",
        team2: "SUE",
        group: "f",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#D52B1E",
        team1_away_color: "#ffffff",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
    {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "BEL",
        team2: "PAN",
        group: "g",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "TUN",
        team2: "ING",
        group: "g",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "14:00",
        team1: "POL",
        team2: "SEN",
        group: "h",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "COL",
        team2: "JPN",
        group: "h",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#fcc41a",
        team1_away_color: "#002B7F",
        team2_home_color: "#ffffff",
        team2_away_color: "#be0000",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "BEL",
        team2: "TUN",
        group: "g",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "ING",
        team2: "PAN",
        group: "g",
        team1_win: 1,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "11:00",
        team1: "POL",
        team2: "COL",
        group: "h",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "JPN",
        team2: "SEN",
        group: "h",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "ING",
        team2: "BEL",
        group: "g",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "PAN",
        team2: "TUN",
        group: "g",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "JPN",
        team2: "POL",
        group: "h",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#00B140",
        team2_away_color: "#FDDA24",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "SEN",
        team2: "COL",
        group: "h",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#D52B1E",
        team1_away_color: "#ffffff",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    }
];

globalData.teams = {
    RUS: {
        country_id: "RUS",
        country: "Rusia",
        group: "a",
        win_group: "0.0",
        sixteen: "1.0",
        quarter: "0.0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#a81717",
        color_away: "#ffffff"
    },
    SAU: {
        country_id: "SAU",
        country: "Arabia Saudita",
        group: "a",
        win_group: "0",
        sixteen: "0",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#1D8348",
        color_away: "#0000FF"
    },
    EGI:{
        country_id:"EGI",
        country:"Egipto",
        group:"a",
        win_group:"0",
        sixteen:"0",
        quarter:"0",
        semi:"1",
        cup:"0.6546546546",
        win:"0.3",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#771125",
        color_away:"#ffffff"
    },
    URU: {
        country_id: "URU",
        country: "Uruguay",
        group: "a",
        win_group: "1",
        sixteen: "1",
        quarter: "0.114641911",
        semi: "1",
        cup: "0.28",
        win: "0.13",
        spi: "76.87",
        spi_offense: "1.5538",
        spi_defense: "0.6937",
        color_home: "#3498DB",
        color_away: "#CE1126"
    },
    POR: {
        country_id: "POR",
        country: "Portugal",
        group: "b",
        win_group: "0",
        sixteen: "1",
        quarter: "0.051268635",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "71.26",
        spi_offense: "1.4788",
        spi_defense: "0.9932",
        color_home: "#A93226",
        color_away: "#FDDA24"
    },
    ESP: {
        country_id: "ESP",
        country: "España",
        group: "b",
        win_group: "1",
        sixteen: "1",
        quarter: "0.328775677",
        semi: "1",
        cup: "0.111807328",
        win: "0.23",
        spi: "86.71",
        spi_offense: "2.7107",
        spi_defense: "0.7041",
        color_home: "#FF0000",
        color_away: "#ffffff"
    },
    MAR: {
        country_id: "MAR",
        country: "Marruecos",
        group: "b",
        win_group: "0",
        sixteen: "0",
        quarter: "0.009704662",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#922B21",
        color_away: "#002B7F"
    },
    IRN:{
        country_id:"IRN",
        country:"Irán",
        group:"b",
        win_group:"0",
        sixteen:"0",
        quarter:"0.691590748",
        semi:"1",
        cup:"0.199066365",
        win:"0.33",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#04B431",
        color_away:"#be0000"
    },
    FRA: {
        country_id: "FRA",
        country: "Francia",
        group: "c",
        win_group: "1",
        sixteen: "1",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#0B0B61",
        color_away: "#ffffff"
    },
    AUS: {
        country_id: "AUS",
        country: "Australia",
        group: "c",
        win_group: "0",
        sixteen: "0",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#F1C40F",
        color_away: "#0000FF"
    },
    PER:{
        country_id:"PER",
        country:"Perú",
        group:"c",
        win_group:"0",
        sixteen:"0",
        quarter:"0.239154256",
        semi:"1",
        cup:"0.6546546546",
        win:"0.3",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#FF0000",
        color_away:"#ffffff"
    },
    DIN: {
        country_id: "DIN",
        country: "Dinamarca",
        group: "c",
        win_group: "0",
        sixteen: "1",
        quarter: "0.114641911",
        semi: "1",
        cup: "0.28",
        win: "0.13",
        spi: "76.87",
        spi_offense: "1.5538",
        spi_defense: "0.6937",
        color_home: "#B40404",
        color_away: "#CE1126"
    },
    ARG: {
        country_id: "ARG",
        country: "Argentina",
        group: "d",
        win_group: "0",
        sixteen: "1",
        quarter: "0.4026",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "71.26",
        spi_offense: "1.4788",
        spi_defense: "0.9932",
        color_home: "#3498DB",
        color_away: "#FDDA24"
    },
    ISL: {
        country_id: "ISL",
        country: "Islandia",
        group: "d",
        win_group: "0.0000",
        sixteen: "0",
        quarter: "0.0258",
        semi: "1",
        cup: "0.111807328",
        win: "0.23",
        spi: "86.71",
        spi_offense: "2.7107",
        spi_defense: "0.7041",
        color_home: "#0404B4",
        color_away: "#ffffff"
    },
    CRO: {
        country_id: "CRO",
        country: "Croacia",
        group: "d",
        win_group: "1",
        sixteen: "1",
        quarter: "0.009704662",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#FE2E2E",
        color_away: "#002B7F"
    },
    NGA:{
        country_id:"NGA",
        country:"Nigeria",
        group:"d",
        win_group:"0.000",
        sixteen:"0",
        quarter:"0.691590748",
        semi:"1",
        cup:"0.199066365",
        win:"0.33",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#04B431",
        color_away:"#be0000"
    },
    BRA: {
        country_id: "BRA",
        country: "Brasil",
        group: "e",
        win_group: "1",
        sixteen: "1",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#FFFF00",
        color_away: "#ffffff"
    },
    SUI: {
        country_id: "SUI",
        country: "Suiza",
        group: "e",
        win_group: "0",
        sixteen: "1",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#DF0101",
        color_away: "#0000FF"
    },
    CRC:{
        country_id:"CRC",
        country:"Costa Rica",
        group:"e",
        win_group:"0.0000",
        sixteen:"0.0000",
        quarter:"0.239154256",
        semi:"1",
        cup:"0.6546546546",
        win:"0.3",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#0101DF",
        color_away:"#ffffff"
    },
    SRB: {
        country_id: "SRB",
        country: "Serbia",
        group: "e",
        win_group: "0",
        sixteen: "0",
        quarter: "0.114641911",
        semi: "1",
        cup: "0.28",
        win: "0.13",
        spi: "76.87",
        spi_offense: "1.5538",
        spi_defense: "0.6937",
        color_home: "#8A0808",
        color_away: "#CE1126"
    },
    GER: {
        country_id: "GER",
        country: "Alemania",
        group: "f",
        win_group: "0",
        sixteen: "0",
        quarter: "0.051268635",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "71.26",
        spi_offense: "1.4788",
        spi_defense: "0.9932",
        color_home: "#000000",
        color_away: "#FDDA24"
    },
    MEX: {
        country_id: "MEX",
        country: "México",
        group: "f",
        win_group: "0",
        sixteen: "1",
        quarter: "0.328775677",
        semi: "1",
        cup: "0.111807328",
        win: "0.23",
        spi: "86.71",
        spi_offense: "2.7107",
        spi_defense: "0.7041",
        color_home: "#088A08",
        color_away: "#ffffff"
    },
    SUE: {
        country_id: "SUE",
        country: "Suecia",
        group: "f",
        win_group: "1",
        sixteen: "1",
        quarter: "0.009704662",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#FFFF00",
        color_away: "#002B7F"
    },
    COR:{
        country_id:"COR",
        country:"Corea",
        group:"f",
        win_group:"0",
        sixteen:"0",
        quarter:"0.691590748",
        semi:"1",
        cup:"0.199066365",
        win:"0.33",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#DF0101",
        color_away:"#be0000"
    },
    BEL: {
        country_id: "BEL",
        country: "Bélgica",
        group: "g",
        win_group: "1",
        sixteen: "1",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#8A0808",
        color_away: "#ffffff"
    },
    PAN: {
        country_id: "PAN",
        country: "Panamá",
        group: "g",
        win_group: "0.0000",
        sixteen: "0.0000",
        quarter: "0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "80.7",
        spi_offense: "1.0",
        spi_defense: "0",
        color_home: "#DF0101",
        color_away: "#0000FF"
    },
    TUN:{
        country_id:"TUN",
        country:"Túnez",
        group:"g",
        win_group:"0.0000",
        sixteen:"0.0000",
        quarter:"0.239154256",
        semi:"1",
        cup:"0.6546546546",
        win:"0.3",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#DF0101",
        color_away:"#ffffff"
    },
    ING: {
        country_id: "ING",
        country: "Inglaterra",
        group: "g",
        win_group: "0",
        sixteen: "1",
        quarter: "0.0",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "76.87",
        spi_offense: "1.5538",
        spi_defense: "0.6937",
        color_home: "#FFFFFF",
        color_away: "#CE1126"
    },
    POL: {
        country_id: "POL",
        country: "Polonia",
        group: "h",
        win_group: "0.0",
        sixteen: "0.0",
        quarter: "0.051268635",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "71.26",
        spi_offense: "1.4788",
        spi_defense: "0.9932",
        color_home: "#DF0101",
        color_away: "#FDDA24"
    },
    SEN: {
        country_id: "SEN",
        country: "Senegal",
        group: "h",
        win_group: "0",
        sixteen: "0",
        quarter: "0.328775677",
        semi: "1",
        cup: "0.111807328",
        win: "0.23",
        spi: "86.71",
        spi_offense: "2.7107",
        spi_defense: "0.7041",
        color_home: "#088A08",
        color_away: "#ffffff"
    },
    COL: {
        country_id: "COL",
        country: "Colombia",
        group: "h",
        win_group: "1",
        sixteen: "1",
        quarter: "0.009704662",
        semi: "0",
        cup: "0",
        win: "0",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#fcc41a",
        color_away: "#002B7F"
    },
    JPN:{
        country_id:"JPN",
        country:"Japón",
        group:"h",
        win_group:"0",
        sixteen:"1",
        quarter:"0.691590748",
        semi:"1",
        cup:"0.199066365",
        win:"0.33",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#0404B4",
        color_away:"#be0000"
    }
};
