var globalData = {};

globalData.matches = [
    {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "BRA",
        team2: "BOL",
        group: "a",
        team1_win: 0.7,
        team2_win: 0.3,
        tie_prob: 0.00000000,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "VEN",
        team2: "PER",
        group: "a",
        team1_win: 0.8,
        team2_win: 0.1,
        tie_prob: 0.2,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "BOL",
        team2: "PER",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "BRA",
        team2: "VEN",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:    0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "BOL",
        team2: "VEN",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "PER",
        team2: "BRA",
        group: "a",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "11:00",
        team1: "ARG",
        team2: "COL",
        group: "b",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "PAR",
        team2: "CAT",
        group: "b",
        team1_win: 0.0,
        team2_win:  1.0,
        tie_prob:   0.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },

        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "COL",
        team2: "CAT",
        group: "b",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#ffffff",
        team1_away_color: "#be0000",
        team2_home_color: "#00B140",
        team2_away_color: "#FDDA24",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "14:00",
        team1: "ARG",
        team2: "PAR",
        group: "b",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#00B140",
        team1_away_color: "#FDDA24",
        team2_home_color: "#D52B1E",
        team2_away_color: "#ffffff",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "CAT",
        team2: "ARG",
        group: "b",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#fcc41a",
        team1_away_color: "#002B7F",
        team2_home_color: "#ffffff",
        team2_away_color: "#be0000",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2017-06-25",
        time_est: "11:00",
        team1: "COL",
        team2: "PAR",
        group: "b",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#D52B1E",
        team1_away_color: "#ffffff",
        team2_home_color: "#fcc41a",
        team2_away_color: "#002B7F",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-14",
        time_est: "11:00",
        team1: "URU",
        team2: "ECU",
        group: "C",
        team1_win: 1.0,
        team2_win: 0.0,
        tie_prob: 0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-15",
        time_est: "11:00",
        team1: "JPN",
        team2: "CHI",
        group: "c",
        team1_win: 0.0,
        team2_win: 1.0,
        tie_prob: 0.0,
        team1_home_color: "#771125",
        team1_away_color: "#ffffff",
        team2_home_color: "#006847",
        team2_away_color: "#CE1126",
        slot: 1,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-19",
        time_est: "11:00",
        team1: "URU",
        team2: "JPN",
        group: "c",
        team1_win: 1.0,
        team2_win:  0.0,
        tie_prob:   0.0,
        team1_home_color: "#a81717",
        team1_away_color: "#ffffff",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-20",
        time_est: "14:00",
        team1: "ECU",
        team2: "CHI",
        group: "c",
        team1_win: 0.0,
        team2_win: 0.0,
        tie_prob: 1.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#e9ebea",
        team2_away_color: "#262930",
        slot: 2,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "CHI",
        team2: "URU",
        group: "c",
        team1_win: 0.0,
        team2_win:  0.0,
        tie_prob:   1.0,
        team1_home_color: "#006847",
        team1_away_color: "#CE1126",
        team2_home_color: "#a81717",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    },
        {
        date: "2018-06-25",
        time_est: "11:00",
        team1: "ECU",
        team2: "JPN",
        group: "c",
        team1_win: 0.0,
        team2_win:  0.8,
        tie_prob:   0.0,
        team1_home_color: "#e9ebea",
        team1_away_color: "#262930",
        team2_home_color: "#771125",
        team2_away_color: "#ffffff",
        slot: 3,
        annotation: "some text here about the game and other smart things we would say"
    }
];

globalData.teams = {
    BOL: {
        country_id: "BOL",
        country: "Bolivia",
        group: "a",
        win_group: "0.8",
        sixteen: "0",
        quarter: "17.6",
        semi: "3",
        cup: "0.3",
        win: "0.0",
        spi: "",
        spi_offense: "",
        spi_defense: "",
        color_home: "#088A08",
        color_away: "#CE1126"
    },
    BRA: {
        country_id: "BRA",
        country: "Brasil",
        group: "a",
        win_group: "75.8",
        sixteen: "0",
        quarter: "98.8",
        semi: "79.2",
        cup: "60.5",
        win: "45.5",
        spi: "",
        spi_offense: "0",
        spi_defense: "0",
        color_home: "#FFFF00",
        color_away: "#ffffff"
    },
    PER:{
        country_id:"PER",
        country:"Perú",
        group:"a",
        win_group:"17.7",
        sixteen:"0",
        quarter:"85",
        semi:"44.1",
        cup:"15.1",
        win:"6.4",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#FF0000",
        color_away:"#ffffff"
    },
    VEN:{
        country_id:"VEN",
        country:"Venezuela",
        group:"a",
        win_group:"5.7",
        sixteen:"0",
        quarter:"59.5",
        semi:"21.1",
        cup:"5.2",
        win:"1.2",
        spi:"79.78",
        spi_offense:"1.9905",
        spi_defense:"0.8046",
        color_home:"#8A0808",
        color_away:"#ffffff"
    },
    ARG: {
        country_id: "ARG",
        country: "Argentina",
        group: "b",
        win_group: "50",
        sixteen: "0",
        quarter: "93",
        semi: "57.8",
        cup: "32.5",
        win: "15.5",
        spi: "71.26",
        spi_offense: "1.4788",
        spi_defense: "0.9932",
        color_home: "#3498DB",
        color_away: "#FDDA24"
    },
    COL: {
        country_id: "COL",
        country: "Colombia",
        group: "b",
        win_group: "1",
        sixteen: "1",
        quarter: "0.8",
        semi: "0.4",
        cup: "0.3",
        win: "0.1",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#fcc41a",
        color_away: "#002B7F"
    },
    PAR: {
        country_id: "PAR",
        country: "Paraguay",
        group: "b",
        win_group: "6.3",
        sixteen: "0",
        quarter: "45.9",
        semi: "13.2",
        cup: "3",
        win: "0.6",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#FF0000",
        color_away: "#002B7F"
    },
    CAT: {
        country_id: "CAT",
        country: "Catar",
        group: "b",
        win_group: "4.5",
        sixteen: "0",
        quarter: "36.2",
        semi: "8.9",
        cup: "1.6",
        win: "0.3",
        spi: "69.44",
        spi_offense: "1.6398",
        spi_defense: "1.2349",
        color_home: "#8A0808",
        color_away: "#002B7F"
    },
    CHI:{
        country_id:"CHI",
        country:"Chile",
        group:"c",
        win_group:"0.30",
        sixteen:"0",
        quarter:"0.76",
        semi:"0.36",
        cup:"0.17",
        win:"0.06",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#FF0000",
        color_away:"#be0000"
    },
    ECU:{
        country_id:"ECU",
        country:"Ecuador",
        group:"c",
        win_group:"0.21",
        sixteen:"0",
        quarter:"0.66",
        semi:"0.26",
        cup:"0.10",
        win:"0.3",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#fcc41a",
        color_away:"#be0000"
    },
    JPN:{
        country_id:"JPN",
        country:"Japón",
        group:"c",
        win_group:"0.13",
        sixteen:"0",
        quarter:"0.52",
        semi:"0.17",
        cup:"0.06",
        win:"0.02",
        spi:"88.91",
        spi_offense:"3.1989",
        spi_defense:"0.7744",
        color_home:"#0404B4",
        color_away:"#be0000"
    },
    URU: {
        country_id: "URU",
        country: "Uruguay",
        group: "c",
        win_group: "0.35",
        sixteen: "0",
        quarter: "0.80",
        semi: "0.41",
        cup: "0.21",
        win: "0.08",
        spi: "76.87",
        spi_offense: "1.5538",
        spi_defense: "0.6937",
        color_home: "#3498DB",
        color_away: "#CE1126"
    }
};
