var globalData = {};

globalData.matches = [
    {
        "date": "2018-06-14",
        "time_est": "11:00",
        "team1": "BRA",
        "team2": "BOL",
        "group": "a",
        "team1_win": 1.00,
        "team2_win": 0.00,
        "tie_prob": 0.00,
        "team1_home_color": "#a81717",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#e9ebea",
        "team2_away_color": "#262930",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-15",
        "time_est": "11:00",
        "team1": "VEN",
        "team2": "PER",
        "group": "a",
        "team1_win": 0.00,
        "team2_win": 0.00,
        "tie_prob": 1.00,
        "team1_home_color": "#771125",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#006847",
        "team2_away_color": "#CE1126",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-20",
        "time_est": "11:00",
        "team1": "ARG",
        "team2": "COL",
        "group": "b",
        "team1_win": 0.00,
        "team2_win": 1.00,
        "tie_prob": 0.00,
        "team1_home_color": "#00B140",
        "team1_away_color": "#FDDA24",
        "team2_home_color": "#fcc41a",
        "team2_away_color": "#002B7F",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-20",
        "time_est": "14:00",
        "team1": "PAR",
        "team2": "CAT",
        "group": "b",
        "team1_win": 0.40,
        "team2_win": 0.34,
        "tie_prob": 0.25,
        "team1_home_color": "#ffffff",
        "team1_away_color": "#be0000",
        "team2_home_color": "#D52B1E",
        "team2_away_color": "#ffffff",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-14",
        "time_est": "11:00",
        "team1": "URU",
        "team2": "ECU",
        "group": "C",
        "team1_win": 0.45,
        "team2_win": 0.29,
        "tie_prob": 0.26,
        "team1_home_color": "#a81717",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#e9ebea",
        "team2_away_color": "#262930",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-15",
        "time_est": "11:00",
        "team1": "JPN",
        "team2": "CHI",
        "group": "c",
        "team1_win": 0.26,
        "team2_win": 0.50,
        "tie_prob": 0.24,
        "team1_home_color": "#771125",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#006847",
        "team2_away_color": "#CE1126",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-19",
        "time_est": "11:00",
        "team1": "BOL",
        "team2": "PER",
        "group": "a",
        "team1_win": 0.10,
        "team2_win": 0.72,
        "tie_prob": 0.18,
        "team1_home_color": "#a81717",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#771125",
        "team2_away_color": "#ffffff",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-20",
        "time_est": "14:00",
        "team1": "BRA",
        "team2": "VEN",
        "group": "a",
        "team1_win": 0.75,
        "team2_win": 0.07,
        "tie_prob": 0.18,
        "team1_home_color": "#006847",
        "team1_away_color": "#CE1126",
        "team2_home_color": "#e9ebea",
        "team2_away_color": "#262930",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2017-06-25",
        "time_est": "11:00",
        "team1": "COL",
        "team2": "CAT",
        "group": "b",
        "team1_win": 0.67,
        "team2_win": 0.13,
        "tie_prob": 0.20,
        "team1_home_color": "#ffffff",
        "team1_away_color": "#be0000",
        "team2_home_color": "#00B140",
        "team2_away_color": "#FDDA24",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-15",
        "time_est": "14:00",
        "team1": "ARG",
        "team2": "PAR",
        "group": "b",
        "team1_win": 0.66,
        "team2_win": 0.13,
        "tie_prob": 0.21,
        "team1_home_color": "#00B140",
        "team1_away_color": "#FDDA24",
        "team2_home_color": "#D52B1E",
        "team2_away_color": "#ffffff",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-19",
        "time_est": "11:00",
        "team1": "URU",
        "team2": "JPN",
        "group": "c",
        "team1_win": 0.51,
        "team2_win": 0.24,
        "tie_prob": 0.25,
        "team1_home_color": "#a81717",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#771125",
        "team2_away_color": "#ffffff",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-20",
        "time_est": "14:00",
        "team1": "ECU",
        "team2": "CHI",
        "group": "c",
        "team1_win": 0.32,
        "team2_win": 0.44,
        "tie_prob": 0.25,
        "team1_home_color": "#006847",
        "team1_away_color": "#CE1126",
        "team2_home_color": "#e9ebea",
        "team2_away_color": "#262930",
        "slot": 2,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-25",
        "time_est": "11:00",
        "team1": "BOL",
        "team2": "VEN",
        "group": "a",
        "team1_win": 0.19,
        "team2_win": 0.58,
        "tie_prob": 0.22,
        "team1_home_color": "#006847",
        "team1_away_color": "#CE1126",
        "team2_home_color": "#a81717",
        "team2_away_color": "#ffffff",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-25",
        "time_est": "11:00",
        "team1": "PER",
        "team2": "BRA",
        "group": "a",
        "team1_win": 0.13,
        "team2_win": 0.60,
        "tie_prob": 0.27,
        "team1_home_color": "#e9ebea",
        "team1_away_color": "#262930",
        "team2_home_color": "#771125",
        "team2_away_color": "#ffffff",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-15",
        "time_est": "11:00",
        "team1": "CAT",
        "team2": "ARG",
        "group": "b",
        "team1_win": 0.11,
        "team2_win": 0.72,
        "tie_prob": 0.17,
        "team1_home_color": "#fcc41a",
        "team1_away_color": "#002B7F",
        "team2_home_color": "#ffffff",
        "team2_away_color": "#be0000",
        "slot": 1,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2017-06-25",
        "time_est": "11:00",
        "team1": "COL",
        "team2": "PAR",
        "group": "b",
        "team1_win": 0.61,
        "team2_win": 0.15,
        "tie_prob": 0.24,
        "team1_home_color": "#D52B1E",
        "team1_away_color": "#ffffff",
        "team2_home_color": "#fcc41a",
        "team2_away_color": "#002B7F",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-25",
        "time_est": "11:00",
        "team1": "CHI",
        "team2": "URU",
        "group": "c",
        "team1_win": 0.34,
        "team2_win": 0.40,
        "tie_prob": 0.27,
        "team1_home_color": "#006847",
        "team1_away_color": "#CE1126",
        "team2_home_color": "#a81717",
        "team2_away_color": "#ffffff",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    },
        {
        "date": "2018-06-25",
        "time_est": "11:00",
        "team1": "ECU",
        "team2": "JPN",
        "group": "c",
        "team1_win": 0.43,
        "team2_win": 0.32,
        "tie_prob": 0.25,
        "team1_home_color": "#e9ebea",
        "team1_away_color": "#262930",
        "team2_home_color": "#771125",
        "team2_away_color": "#ffffff",
        "slot": 3,
        "annotation": "some text here about the game and other smart things we would say"
    }
];

globalData.teams = {
    "BOL": {
        "country_id": "BOL",
         "country": "Bolivia",
        "group": "a",
        "win_group": "0.00",
        "sixteen": "0.07",
        "quarter": "0.15",
        "semi": "0.03",
        "cup": "0.00",
        "win": "0.00",
        "spi": "",
         "spi_offense": "",
         "spi_defense": "",
         "color_home": "#088A08",
         "color_away": "#CE1126"
    },
    "BRA": {
        "country_id": "BRA",
         "country": "Brasil",
        "group": "a",
        "win_group": "0.84",
        "sixteen": "0.12",
        "quarter": "1.00",
        "semi": "0.80",
        "cup": "0.61",
        "win": "0.46",
        "spi": "",
         "spi_offense": "0",
         "spi_defense": "0",
         "color_home": "#FFFF00",
         "color_away": "#ffffff"
    },
    "PER":{
        "country_id": "PER",
         "country":"Perú",
        "group":"a",
        "win_group": "0.11",
        "sixteen": "0.50",
        "quarter": "0.81",
        "semi": "0.42",
        "cup": "0.15",
        "win": "0.06",
        "spi":"79.78",
         "spi_offense":"1.9905",
         "spi_defense":"0.8046",
         "color_home":"#FF0000",
         "color_away":"#ffffff"
    },
    "VEN":{
        "country_id": "VEN",
         "country":"Venezuela",
        "group":"a",
        "win_group": "0.05",
        "sixteen": "0.31",
        "quarter": "0.66",
        "semi": "0.23",
        "cup": "0.06",
        "win": "0.01",
        "spi":"79.78",
         "spi_offense":"1.9905",
         "spi_defense":"0.8046",
         "color_home":"#8A0808",
         "color_away":"#ffffff"
    },
    "ARG": {
        "country_id": "ARG",
         "country": "Argentina",
        "group": "b",
        "win_group": "0.09",
        "sixteen": "0.56",
        "quarter": "0.83",
        "semi": "0.51",
        "cup": "0.24",
        "win": "0.13",
        "spi": "71.26",
         "spi_offense": "1.4788",
         "spi_defense": "0.9932",
         "color_home": "#3498DB",
         "color_away": "#FDDA24"
    },
    "COL": {
        "country_id": "COL",
         "country": "Colombia",
        "group": "b",
        "win_group": "0.81",
        "sixteen": "0.14",
        "quarter": "0.99",
        "semi": "0.59",
        "cup": "0.34",
        "win": "0.14",
        "spi": "69.44",
         "spi_offense": "1.6398",
         "spi_defense": "1.2349",
         "color_home": "#fcc41a",
         "color_away": "#002B7F"
    },
    "PAR": {
        "country_id": "PAR",
         "country": "Paraguay",
        "group": "b",
        "win_group": "0.05",
        "sixteen": "0.17",
        "quarter": "0.46",
        "semi": "0.13",
        "cup": "0.03",
        "win": "0.01",
        "spi": "69.44",
         "spi_offense": "1.6398",
         "spi_defense": "1.2349",
         "color_home": "#FF0000",
         "color_away": "#002B7F"
    },
    "CAT": {
        "country_id": "CAT",
         "country": "Catar",
        "group": "b",
        "win_group": "0.04",
        "sixteen": "0.13",
        "quarter": "0.36",
        "semi": "0.09",
        "cup": "0.02",
        "win": "0.00",
        "spi": "69.44",
         "spi_offense": "1.6398",
         "spi_defense": "1.2349",
         "color_home": "#8A0808",
         "color_away": "#002B7F"
    },
    "CHI":{
        "country_id": "CHI",
         "country":"Chile",
        "group":"c",
        "win_group": "0.31",
        "sixteen": "0.28",
        "quarter": "0.76",
        "semi": "0.36",
        "cup": "0.18",
        "win": "0.06",
        "spi":"88.91",
         "spi_offense":"3.1989",
         "spi_defense":"0.7744",
         "color_home":"#FF0000",
         "color_away":"#be0000"
    },
    "ECU":{
        "country_id": "ECU",
         "country":"Ecuador",
        "group":"c",
        "win_group": "0.21",
        "sixteen": "0.25",
        "quarter": "0.65",
        "semi": "0.26",
        "cup": "0.11",
        "win": "0.03",
        "spi":"88.91",
         "spi_offense":"3.1989",
         "spi_defense":"0.7744",
         "color_home":"#fcc41a",
         "color_away":"#be0000"
    },
    "JPN":{
        "country_id": "JPN",
         "country":"Japón",
        "group":"c",
        "win_group": "0.13",
        "sixteen": "0.20",
        "quarter": "0.52",
        "semi": "0.17",
        "cup": "0.06",
        "win": "0.02",
        "spi":"88.91",
         "spi_offense":"3.1989",
         "spi_defense":"0.7744",
         "color_home":"#0404B4",
         "color_away":"#be0000"
    },
    "URU": {
        "country_id": "URU",
         "country": "Uruguay",
        "group": "c",
        "win_group": "0.35",
        "sixteen": "0.28",
        "quarter": "0.80",
        "semi": "0.41",
        "cup": "0.22",
        "win": "0.08",
        "spi": "76.87",
         "spi_offense": "1.5538",
         "spi_defense": "0.6937",
         "color_home": "#3498DB",
         "color_away": "#CE1126"
    }
};
